version: '3.4'

services:
  consignee:
    image: customer-consignee
    build:
      context: .
      dockerfile: Consignee/Dockerfile

  soldto:
    image: customer-soldto
    build:
      context: .
      dockerfile: SoldTo/Dockerfile


  carrier:
    image: customer-carrier
    build:
      context: .
      dockerfile: Carrier/Dockerfile


  orders:
    image: customer-orders
    build:
      context: .
      dockerfile: Orders/Dockerfile

